
language: python

os: linux

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get install -y build-essential gdal-bin libgdal-dev libproj-dev
  - pip install rasterio
  - pip install poetry

install:
  - travis_retry pip install poetry

addons:
  apt:
    update: true

script:
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)
